import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.blueGray50,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray100,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.orange800,
          fontSize: 16.fSize,
          fontFamily: 'JetBrains Mono',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onError,
          fontSize: 13.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray700,
          fontSize: 11.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.primaryContainer.withOpacity(1),
          fontSize: 30.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: colorScheme.primary,
          fontSize: 13.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.redA200,
          fontSize: 20.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primaryContainer.withOpacity(1),
          fontSize: 18.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: colorScheme.primaryContainer.withOpacity(1),
          fontSize: 14.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFFF9214),
    primaryContainer: Color(0XCC212529),
    secondary: Color(0XCC212529),
    secondaryContainer: Color(0XFFFF6B6B),
    tertiary: Color(0XCC212529),
    tertiaryContainer: Color(0XFFFF6B6B),

    // Background colors
    background: Color(0XCC212529),

    // Surface colors
    surface: Color(0XCC212529),
    surfaceTint: Color(0XFF0E1629),
    surfaceVariant: Color(0XFFFF6B6B),

    // Error colors
    error: Color(0XFF0E1629),
    errorContainer: Color(0XFFF03E3E),
    onError: Color(0XFF868E96),
    onErrorContainer: Color(0XFF0E1629),

    // On colors(text colors)
    onBackground: Color(0XFFCED4DA),
    onInverseSurface: Color(0XFF868E96),
    onPrimary: Color(0XFF0E1629),
    onPrimaryContainer: Color(0XFFCED4DA),
    onSecondary: Color(0XFFCED4DA),
    onSecondaryContainer: Color(0XFF0E1629),
    onTertiary: Color(0XFFCED4DA),
    onTertiaryContainer: Color(0XFF0E1629),

    // Other colors
    outline: Color(0XFF0E1629),
    outlineVariant: Color(0XCC212529),
    scrim: Color(0XCC212529),
    shadow: Color(0XFF0E1629),

    // Inverse colors
    inversePrimary: Color(0XCC212529),
    inverseSurface: Color(0XFF0E1629),

    // Pending colors
    onSurface: Color(0XFFCED4DA),
    onSurfaceVariant: Color(0XFF0E1629),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray200 => Color(0XFFADB5BD);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray50 => Color(0XFFE9ECEF);
  Color get blueGray700 => Color(0XFF495057);

  // Gray
  Color get gray100 => Color(0XFFF1F3F5);
  Color get gray300 => Color(0XFFDEE2E6);
  Color get gray50 => Color(0XFFF8F9FA);
  Color get gray5001 => Color(0XFFFFF5F5);
  Color get gray800 => Color(0XFF343A40);

  // Green
  Color get green300 => Color(0XFF69DB7C);
  Color get green400 => Color(0XFF51CF66);
  Color get green50 => Color(0XFFEBFBEE);
  Color get green500 => Color(0XFF37B24D);

  // Orange
  Color get orange200 => Color(0XFFFFBE72);
  Color get orange400 => Color(0XFFFF922B);
  Color get orange50 => Color(0XFFFFF4E8);
  Color get orange5001 => Color(0XFFFFF4E6);
  Color get orange5002 => Color(0XFFFFE9D0);
  Color get orange800 => Color(0XFFCC7510);

  // Red
  Color get redA200 => Color(0XFFFA5252);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);

  // Yellowc
  Color get yellow9000c => Color(0X0CD98C33);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
