import 'bloc/help_center_three_bloc.dart';import 'models/help_center_three_model.dart';import 'package:carat_card/core/app_export.dart';import 'package:carat_card/widgets/app_bar/appbar_image_1.dart';import 'package:carat_card/widgets/app_bar/appbar_subtitle.dart';import 'package:carat_card/widgets/app_bar/custom_app_bar.dart';import 'package:carat_card/widgets/custom_icon_button.dart';import 'package:carat_card/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class HelpCenterThreeScreen extends StatelessWidget {const HelpCenterThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HelpCenterThreeBloc>(create: (context) => HelpCenterThreeBloc(HelpCenterThreeState(helpCenterThreeModelObj: HelpCenterThreeModel()))..add(HelpCenterThreeInitialEvent()), child: HelpCenterThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<HelpCenterThreeBloc, HelpCenterThreeState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 38.v, leadingWidth: 44.h, leading: AppbarImage1(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 20.h, bottom: 1.v), onTap: () {onTapArrowleftone(context);}), title: AppbarSubtitle(text: "lbl_help_center".tr, margin: EdgeInsets.only(left: 12.h))), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 15.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700)), Container(padding: EdgeInsets.all(20.h), child: Column(children: [Container(padding: EdgeInsets.all(20.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_i_cannot_do_this".tr, style: theme.textTheme.titleSmall), SizedBox(height: 26.v), SizedBox(width: 310.h, child: Text("msg_eget_gravida_laoreet".tr, maxLines: 16, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray700.copyWith(height: 1.43))), Padding(padding: EdgeInsets.only(top: 25.v, right: 82.h), child: Row(children: [CustomOutlinedButton(height: 32.v, width: 96.h, text: "lbl_helpful".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(svgPath: ImageConstant.imgHeroiconsminiHandthumbup)), buttonStyle: CustomButtonStyles.outlineBlueGrayTL16, buttonTextStyle: CustomTextStyles.bodyMediumPrimaryContainer), CustomOutlinedButton(height: 32.v, width: 120.h, text: "lbl_not_helpful".tr, margin: EdgeInsets.only(left: 12.h), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(svgPath: ImageConstant.imgHeroiconsminiHandthumbdown)), buttonStyle: CustomButtonStyles.outlineBlueGrayTL16, buttonTextStyle: CustomTextStyles.bodyMediumPrimaryContainer)]))])), SizedBox(height: 20.v), Container(width: 350.h, padding: EdgeInsets.all(20.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_i_need_more_help".tr, style: theme.textTheme.titleSmall), SizedBox(height: 24.v), GestureDetector(onTap: () {onTapCell(context);}, child: Row(children: [CustomIconButton(height: 38.adaptSize, width: 38.adaptSize, padding: EdgeInsets.all(9.h), child: CustomImageView(svgPath: ImageConstant.imgHeroiconsminiPrimary38x38)), Padding(padding: EdgeInsets.only(left: 16.h, top: 10.v, bottom: 10.v), child: Text("lbl_chat_with_us".tr, style: theme.textTheme.titleSmall))]))])), SizedBox(height: 5.v)]))]))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the helpCenterFourScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the helpCenterFourScreen.
onTapCell(BuildContext context) { NavigatorService.pushNamed(AppRoutes.helpCenterFourScreen, ); } 
 }
