import 'bloc/transactions_three_bloc.dart';import 'models/transactions_three_model.dart';import 'package:carat_card/core/app_export.dart';import 'package:carat_card/presentation/dashboard_one_page/dashboard_one_page.dart';import 'package:carat_card/presentation/offer_two_page/offer_two_page.dart';import 'package:carat_card/presentation/rewards_three_page/rewards_three_page.dart';import 'package:carat_card/presentation/transactions_one_page/transactions_one_page.dart';import 'package:carat_card/widgets/custom_bottom_bar.dart';import 'package:carat_card/widgets/custom_drop_down.dart';import 'package:carat_card/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class TransactionsThreeScreen extends StatelessWidget {TransactionsThreeScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<TransactionsThreeBloc>(create: (context) => TransactionsThreeBloc(TransactionsThreeState(transactionsThreeModelObj: TransactionsThreeModel()))..add(TransactionsThreeInitialEvent()), child: TransactionsThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 15.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700)), Padding(padding: EdgeInsets.only(left: 20.h, top: 13.v, right: 20.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgArrowleft, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgArrowleftone(context);}), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("lbl_statement".tr, style: theme.textTheme.titleMedium)), Spacer(), CustomImageView(svgPath: ImageConstant.imgHeroiconsoutlinebell, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgHeroiconsoutlin(context);})])), Container(margin: EdgeInsets.only(left: 20.h, top: 22.v, right: 20.h), padding: EdgeInsets.all(20.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_starting_on".tr, style: CustomTextStyles.bodyMediumBluegray700_1), SizedBox(height: 7.v), BlocSelector<TransactionsThreeBloc, TransactionsThreeState, TransactionsThreeModel?>(selector: (state) => state.transactionsThreeModelObj, builder: (context, transactionsThreeModelObj) {return CustomDropDown(width: 145.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 14.h, 10.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdown)), hintText: "lbl_juy_2023".tr, items: transactionsThreeModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<TransactionsThreeBloc>().add(ChangeDropDownEvent(value: value));});})])), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ending_on".tr, style: CustomTextStyles.bodyMediumBluegray700_1), SizedBox(height: 7.v), BlocSelector<TransactionsThreeBloc, TransactionsThreeState, TransactionsThreeModel?>(selector: (state) => state.transactionsThreeModelObj, builder: (context, transactionsThreeModelObj) {return CustomDropDown(width: 145.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 14.h, 10.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdown)), hintText: "lbl_juy_2023".tr, items: transactionsThreeModelObj?.dropdownItemList1 ?? [], onChanged: (value) {context.read<TransactionsThreeBloc>().add(ChangeDropDown1Event(value: value));});})]))])), Spacer(), CustomElevatedButton(text: "lbl_generate".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 20.v))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.dashboardOnePage; case BottomBarEnum.Account: return AppRoutes.transactionsOnePage; case BottomBarEnum.Rewards: return AppRoutes.rewardsThreePage; case BottomBarEnum.Offers: return AppRoutes.offerTwoPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.dashboardOnePage: return DashboardOnePage.builder(context); case AppRoutes.transactionsOnePage: return TransactionsOnePage.builder(context); case AppRoutes.rewardsThreePage: return RewardsThreePage.builder(context); case AppRoutes.offerTwoPage: return OfferTwoPage.builder(context); default: return DefaultWidget();} } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapImgArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the notificationsTwoScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the notificationsTwoScreen.
onTapImgHeroiconsoutlin(BuildContext context) { NavigatorService.pushNamed(AppRoutes.notificationsTwoScreen, ); } 
 }
