import '../authentication_three_screen/widgets/rowinput_item_widget.dart';import 'bloc/authentication_three_bloc.dart';import 'models/authentication_three_model.dart';import 'models/rowinput_item_model.dart';import 'package:carat_card/core/app_export.dart';import 'package:carat_card/widgets/custom_elevated_button.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class AuthenticationThreeScreen extends StatelessWidget {const AuthenticationThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AuthenticationThreeBloc>(create: (context) => AuthenticationThreeBloc(AuthenticationThreeState(authenticationThreeModelObj: AuthenticationThreeModel()))..add(AuthenticationThreeInitialEvent()), child: AuthenticationThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Container(height: 15.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700)), SizedBox(height: 31.v), CustomImageView(imagePath: ImageConstant.imgEllipse760, height: 42.adaptSize, width: 42.adaptSize, radius: BorderRadius.circular(21.h)), SizedBox(height: 9.v), Text("lbl_john_doe".tr, style: theme.textTheme.titleSmall), SizedBox(height: 45.v), Text("lbl_password".tr, style: theme.textTheme.titleMedium), Container(margin: EdgeInsets.only(left: 20.h, top: 22.v, right: 20.h), padding: EdgeInsets.symmetric(horizontal: 60.h, vertical: 40.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 16.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 6, effect: ScrollingDotsEffect(spacing: 16, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary, dotHeight: 16.v, dotWidth: 16.h))), SizedBox(height: 40.v), BlocBuilder<AuthenticationThreeBloc, AuthenticationThreeState>(builder: (context, state) {return CarouselSlider.builder(options: CarouselOptions(height: 316.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {state.sliderIndex = index;}), itemCount: state.authenticationThreeModelObj?.rowinputItemList.length ?? 0, itemBuilder: (context, index, realIndex) {RowinputItemModel model = state.authenticationThreeModelObj?.rowinputItemList[index] ?? RowinputItemModel(); return RowinputItemWidget(model);});})])), SizedBox(height: 22.v), GestureDetector(onTap: () {onTapTxtUsefingerprint(context);}, child: Text("lbl_use_fingerprint".tr, style: CustomTextStyles.bodyMediumBluegray200_1)), SizedBox(height: 5.v)])), bottomNavigationBar: CustomElevatedButton(text: "lbl_singin".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 41.v), onTap: () {onTapSingin(context);}))); } 
/// Navigates to the dashboardOneContainerScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the dashboardOneContainerScreen.
onTapSingin(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dashboardOneContainerScreen, ); } 
/// Navigates to the authenticationFourScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the authenticationFourScreen.
onTapTxtUsefingerprint(BuildContext context) { NavigatorService.pushNamed(AppRoutes.authenticationFourScreen, ); } 
 }
